#use comlog configure
COMLOG_LEVEL : 16

COMLOG_DEVICE_NUM : 2
#COMLOG_DEVICE : FILE
COMLOG_PROCNAME : mrcp-asr
COMLOG_DEVICE0 : FILE
COMLOG_DEVICE1 : AFILE

#device 0: FILE
FILE_TYPE : ULLOG
#log file 
FILE_NAME : mrcp.log
FILE_PATH : ./log/
SIZE : 214748364700
#log level
FILE_SYSLEVEL : 4
#split log type
FILE_SPLITE_TYPE : DATECUT
#split log by time, the minutes of time interval
FILE_DATA_CUTTIME : 180
QUOTA_DAY : 30
#the format of time, postfix of log filename
FILE_RESERVED1 : %Y%m%d%H
#use this log or not
FILE_OPEN : 1
AFILE_LAYOUT : %A %R

# Device 1: AFILE
# 这是一个异步打印的文件日志，它不会阻塞日志打印的线程
AFILE_TYPE : AFILE
AFILE_NAME : mrcp_debug.log
AFILE_PATH : ./log/
AFILE_SIZE : 214748364700
#split log type
AFILE_SPLITE_TYPE : DATECUT
#split log by time, the minutes of time interval
AFILE_DATA_CUTTIME : 60
QUOTA_DAY : 30
#the format of time, postfix of log filename
AFILE_RESERVED1 : %Y%m%d%H
#use this log or not
AFILE_OPEN : 1
# 默认的格式是：%L: %D:  %P * %T [%N] %R
#AFILE_LAYOUT : | %L | %D | %P | %T | %R |
#AFILE_LAYOUT : %L: %D: %P %T %R
AFILE_LAYOUT : %A %R
AFILE_SYSLEVEL : 16
#AFILE_SELFLEVEL : ML_DEBUG_LOG
