#comlog config
COMLOG_CONF_PATH : ./conf
COMLOG_CONF_FILE : comlog.conf

FRONT_THREAD_COUNT : 100
BACKEND_THREAD_COUNT : 200

#time out config. ms
CONN_TMO : 3000

#read, write timeout, ms
READ_TIMEOUT : 60000
WRITE_TIMEOUT : 10000 

#use bns to manage asr server
USE_BNS : 0
BNS_READ_TIMEOUT : 3000
BNS_MAX_SVR_NUM : 300
BNS_UPDATE_INTERVAL : 180000
BNS_SVR_CONF_FILE : ""
#noah node for bns
@ASR_NOAH_NODE : ""

#offline tts server
$include : offline_asr_svr.conf 

##ASR PARAM
PRODUCT : 1000
CLIENT_REGION : 100
SAMPLE_RATE : 8000
#单位ms
AUDIO_SPLIT_TIME : 160
ACC_160MS_AFTER_VAD : 1

#是否转码, 1: alaw转为pcm8k16bit (默认); 0:不需要转码
NEED_ALAW2PCM : 1

#是否使用解码器, 1:使用(默认); 0:不使用
NEED_ASR_SERVER : 1

#是否保存音频, 1:保存(默认); 0:不保存
NEED_SAVE_AUDIO : 1

NEED_AGC : 0
NEED_SAVE_AGC_AUDIO : 0

#小流量限流检测服务; 未配置时，不检测限流。
#FLOW_LIMIT_SERVER : "http://localhost:8888/ivr/isAbTest?channelId=000000"
FLOW_LIMIT_SERVER : ""

#百度大脑服务, 用于向它推送中间结果；未配置时，不推送。
#BAIDU_BRAIN_SERVER : "http://aikefu-test.baidu.com:8888/ivr/asr"
BAIDU_BRAIN_SERVER : ""

# 用户未说话超时时间ms
NO_INPUT_TIMEOUT : 10000
SPEECH_COMPLETE_TIMEOUT : 20000
# 单句音频的最大时长ms
MAX_SENTENCE_LENGTH : 55000
# 连续识别，用户未说话超时时间ms
MAX_NO_INPUT_TIMEOUT : 7200000

SINGLE_WORD_WHILE_LIST : ./conf/singleword_whitelist.txt
DETECT_START_OF_INPUT_BY_VAD : 1

ASR_SERVER_ADDR : "list://127.0.0.1:8002"
LOADBALANCE_NAME : "random"

XML_ASR_RESULT_VAR_IDENTIFIER : $$$
XML_ASR_RESULT_TEMPLATE : ./conf/xml_asr_result_template.xml

CONNECT_ASR_TIMES : 3
PCM_NEED_WAV_HEAD : 0

CALL_ID_KEY : lmid
PROJECT_NAME : OPENAI
AUDIO_FILE_NAME_VAR_IDENTIFIER : $$$
#wav 文件可配字段有timestamp，call_id，sip_call_id，channel_id，默认是channel_id.wav
#pcm 文件可配字段有timestamp，call_id，sip_call_id，channel_id，request_id，index默认是channel_id+request_id+index.pcm

OPENAI_WAV_FILE_NAME_FORMAT : session_id
OPENAI_PCM_FILE_NAME_FORMAT : session_id$$$request_id

ASR_CON_TYPE : 1
LINK_TYPE_ASR: 3
PRODUCT_ID_ASR : 1134
KEY_ASR : "com.baidu.mrcp.asr"

AUDIO_CONTROLLER_ADDR : "wss://vse.baidu.com/call"
AUTH_APPID : 123
AUTH_APPKEY : "mykey"
