#comlog config
COMLOG_CONF_PATH : ./conf
COMLOG_CONF_FILE : comlog.conf

NEED_SAVE_AUDIO : 1
PCM_NEED_WAV_HEAD : 0

CALL_ID_KEY : lmid
PROJECT_NAME : OPENAI
AUDIO_FILE_NAME_VAR_IDENTIFIER : $$$
#wav 文件可配字段有timestamp，call_id，sip_call_id，channel_id，默认是channel_id.wav
#pcm 文件可配字段有timestamp，call_id，sip_call_id，channel_id，request_id，index默认是channel_id+request_id+index.pcm

OPENAI_WAV_FILE_NAME_FORMAT : session_id
OPENAI_PCM_FILE_NAME_FORMAT : session_id$$$request_id

THREAD_COUNT : 200

#time out config. ms
CONN_TMO : 3000
#read, write timeout, ms
READ_TIMEOUT : 20000
WRITE_TIMEOUT : 3000 
#sub sythesize task timeout
TASK_TIMEOUT_MS : 20000

#rpc retry times
TTS_CONNECT_MAXRETRY : 2
#rpc connection type
CONN_TYPE : single
#rpc connection load balancer
TTS_LOAD_BALANCER : "random"
#cluster of rpc tts servers
TTS_CLUSTER : "list://127.0.0.1:13121"

# only for text server
TEXT_SERVER :

#local audio direcotry
SSML_AUDIO_PATH: ./data
#default speaker id
DEFAULT_SPEAKER_ID : 100

VOICE_SPEED : 5
VOICE_VOLUME : 5
VOICE_PITCH : 5

SAMPLE_RATE : 8000

#enable tts-refiner 0=disable others=enable
TR_ENABLE : 1
TR_RULES_CONFIG : ./data/rules.dat

TTS_CON_TYPE : 1
LINK_TYPE_TTS: 3
PRODUCT_ID_TTS : 5000
KEY_TTS : "com.baidu.mrcp.tts"

AUDIO_CONTROLLER_ADDR : "wss://vse.baidu.com/call"
AUTH_APPID : 123
AUTH_APPKEY : "my-key"

[@VOICE_INFO]
NAME : fduxiaowen
ID : 100

