sp_threshold : 0.2 
sil_threshold : 0.1
max_wait_duration : 80
max_sp_duration : 24000
max_sp_pause : 80
head_sil_duration : 18000
start_back_frame : 40
end_back_frame : 40
debug_log : 0
sample_rate : 8000
cmvnfile : global.cmvn 
dnnfile : vad.dnn
package_len : 1600

vad_num : 10
